name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci-macos:
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache Homebrew packages
      uses: actions/cache@v3
      id: cache-brew
      with:
        path: ~/Library/Caches/Homebrew
        key: ${{ runner.os }}-brew-llvm-${{ hashFiles('.github/workflows/ci_mac.yml') }}
        restore-keys: |
          ${{ runner.os }}-brew-llvm-

    - name: Install LLVM via Homebrew
      run: |
        brew update
        brew install llvm@20
        echo "/opt/homebrew/opt/llvm@20/bin" >> $GITHUB_PATH

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6

    - name: Cache uv dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install dependencies
      run: uv sync

    - name: Install mlir-egglog
      run: uv pip install -e .

    - name: Run Tests
      run: uv run pytest
